### ISSUE TITLE
Upload broken in Chrome

### ISSUE THREAD

**Issue by CoDEmanX** [cjrd/directed-graph-creator#4]
The hosted demo at http://bl.ocks.org/cjrd/6863459 doesn't allow me to upload a previously downloaded graph in Chrome 39 on Windows 8.

It works fine in Firefox.

**Comment by renanlecaro** [comment]
Same here, but i could not manage to make it work in any browser.

I get the following error after loading a graph file and trying to make a new node

![dgc bug](https://cloud.githubusercontent.com/assets/3457214/7338117/b8cb9432-ec41-11e4-824c-e8c5b0dcd145.png)

Json file (anonymized) : 
https://api.myjson.com/bins/4scs1

**Comment by cjrd** [comment]
I'm unable to reproduce. What browser versions / OS versions are you using?

**Comment by CoDEmanX** [comment]
Works for me in Firefox 37 and Chrome 43 on Windows 8.1 64bit, maybe Chrome 39 or bl.ocks.org was broken.
