### ISSUE TITLE
Works unreliably

### ISSUE THREAD

**Issue by jimcullenaus** [cjrd/directed-graph-creator#8]
Very rarely behaves in the manner expected.
- Shift-clicking in an empty space often tries renaming some other node.
- Shift-clicking on a node doesn't reliably start renaming _that_ node.
- Clicking on a node frequently fails to select it, so that pressing delete will do nothing (or delete a _previously_ selected node).

Just about the only feature that works correctly is dragging to connect edges.

**Comment by cjrd** [comment]
Could you provide additional details such as the web browser and operating
system you're using?

**Comment by jimcullenaus** [comment]
Google Chrome on both Ubuntu (well, Kubuntu) and OS X. Though it works far better on OS X than Kubuntu. Renaming things and deleting works about 80% of the time on OS X, versus maybe 20% on Kubuntu, and creating a new node is about 60% successful versus basically never.

In each case, the server is _running_ on Ubuntu.

**Comment by jimcullenaus** [comment]
The issue should not have been closed, because it is still a very real problem.
